### PR TITLE
Support request for PR #1686

### PR DESCRIPTION
**Pull request by chunyou128**
Don't forget to cleanup

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option. 

In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

### CODE REVIEW

**Comment by chunyou128** [comment]
cleanup CriticalSection

**Comment by isaak654** [comment]
If the fix is correct, why not extending it to other files as well? I ask this as a layman.

**Comment by chunyou128** [comment]
This is my first commit.I am not sure I was right。I commited it first，If I was right I will extent it to other files as well.

**Comment by DavidXanatos** [comment]
the fix looks right to me, sandboxies approach to clean up was often, let windows do that when the process dies, that's not pretty.
So please go ahead and add all the missing clean up you can find I'll review it then and merge if everythign looks fine.

**Comment by chunyou128** [comment]
Thanks a lot.I will try my best.

**Comment by chunyou128** [comment]
@DavidXanatos I've created a new pull Request which do not include the sbiedll.dll's change.I can't find a proper place to clean critical section for sbiedll.dll.

**Comment by DavidXanatos** [comment]
> @DavidXanatos I've created a new pull Request which do not include the sbiedll.dll's change.I can't find a proper place to clean critical section for sbiedll.dll: #1686

Well as it stands sbie DLL is not intended to be unloaded anyways, as soon as this woudl happen all hooks will point to noware and the process will crash.

**Pull request closed without merging**
