### PR TITLE
Update sandman_sv_SE.ts

### PR DESCRIPTION
**Pull request by Thatagata**
To be continued

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option. 

In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

### CODE REVIEW

**Comment by Thatagata** [comment]
That should mean i can start again and with that job implemented?

My concern is for the future. If it is much to do i take pauses and since i do not know how to restart the job, i will pull request after request until finished. How will the receiver know when it is done, and, in the middle of my job, it will maybe used in a new release but could be completed just a couple of hours later and by that get the final version in that new release instead.

Do you see what i mean?

This is my main concern.

How do we solve this? When that is solved, well, then it would work.


Per


Den Sun, 27 Aug 2023 07:05:13 -0700, DavidXanatos ***@***.***> skrev:
 
 

Merged #3240 into master.

**Comment by DavidXanatos** [comment]
you can nark pull request as draft so that should solve this issue

**Comment by Thatagata** [comment]
I thought i should try that manouver but, i can not change anything because of - Read only access.

What to do?

**Comment by Thatagata** [comment]
Fixed it!!

**Comment by Thatagata** [comment]
> you can mark pull request as draft so that should solve this issue

How and where do i "Mark" it?

**Comment by isaak654** [comment]
> How and where do i "Mark" it?

It is written here: https://github.com/sandboxie-plus/Sandboxie/pull/3240#issue-1868501686

More specifically:

> it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option.
> 
> In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

This pull request has already been merged, so you won't find the "Convert to draft" link in the right sidebar anymore.

Further information can be found in the GitHub support pages: https://support.github.com/

**Comment by Thatagata** [comment]
Yeah i saw it just before your mail.

So, to summarize. I can pause my work with the Draft option, and when continuing and finishing off - i make a "Pull Request, and that will be it.


Per


Den Sun, 27 Aug 2023 07:51:20 -0700, isaak654 ***@***.***> skrev:
 
 


How and where do i "Mark" it?


It is written here: #3240 (comment)

More specifically:


it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option.

In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".


This pull request has already been merged, so you won't find the "Convert to draft" link in the right sidebar anymore.

Further information can be found in the GitHub support pages: https://support.github.com/

**Comment by Thatagata** [comment]
Hi

It seems that those changes did not get saved since i can not see them in the Master. It looks like before i started.


Per


Den Sun, 27 Aug 2023 07:05:13 -0700, DavidXanatos ***@***.***> skrev:
 
 

Merged #3240 into master.

**Comment by isaak654** [comment]
> So, to summarize. I can pause my work with the Draft option, and when continuing and finishing off - i make a "Pull Request, and that will be it.

I would advise not to pause pull requests for too long, because in the meantime there may be new versions of Sandboxie that introduce new strings to translate in the master branch.

For further questions, please take a look at the GitHub support pages: https://support.github.com/

**Pull request merged**
