### PR TITLE
Add translation

### PR DESCRIPTION
**Pull request by JNylson**
Added Portuguese language

### CODE REVIEW

**Comment by DavidXanatos** [comment]
I have updated the sources to the upcoming build 0.5.3 could you please update the translation, as some english strings have changed

**Comment by DavidXanatos** [comment]
I have updated the sandman sources for the upcoming next build, could you please take a look and update the translation.

**Comment by DavidXanatos** [comment]
I created a slack channel for sandboxie-plus, if you send me an email address than I can send you an invite.
That would be more convenient for communication.

**Comment by JNylson** [comment]
nylsinho_ba@hotmail.com

Atenciosamente Nylson​ Santos
________________________________
De: DavidXanatos <notifications@github.com>
Enviado: sexta-feira, 8 de janeiro de 2021 05:58
Para: sandboxie-plus/Sandboxie <Sandboxie@noreply.github.com>
Cc: JNylson <nylsinho_ba@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [sandboxie-plus/Sandboxie] Add translation (#282)


I created a slack channel for sandboxie-plus, if you send me an email address than I can send you an invite.
That would be more convenient for communication.

**Pull request merged**
