### PR TITLE
Added Portuguese of Portugal

### PR DESCRIPTION
**Pull request by JNylson**

### CODE REVIEW

**Comment by isaak654** [comment]
1) Your change implies that the existing `sandman_pt.ts` file should be renamed as `sandman_pt_BR.ts`.
2) There would be also multiple references to update:
https://github.com/sandboxie-plus/Sandboxie/search?q=sandman_pt
https://github.com/sandboxie-plus/Sandboxie/blob/54580a85480f1cdda805bb69709979a107ba7b35/Installer/Sandboxie-Plus.iss#L213
3) Are you going to maintain both TS files?

**Comment by JNylson** [comment]
My native language is pt_BR, ideally someone was to translate it, but I can try for now

**Comment by JNylson** [comment]
thanks for fixes

**Comment by isaak654** [comment]
I think this should be planned for the next 1.0.8, if nothing else comes up.

**Review by mpheath — APPROVED** [review]
Changed a tab indent that should have been 4 spaces. The iss entries appear OK. I give it a :+1:

**Pull request merged**
