### PR TITLE
Optimized registry residue for deleting services

### PR DESCRIPTION
**Pull request by lmou523**
The current sandbox service has garbage when deleted, I optimized the garbage residue

### CODE REVIEW

**Comment by DavidXanatos** [comment]
The way this works seams intentional, see Scm_GetAllServices it check if the first letter of a service name is '*' and skips it.
also Scm_DeleteService does not remove the actual reg key for the service.

As I wrote the Sandboxie+ Roadmap the entire sandboxed SCM mechanism needs to gets reworked, best would be to rebuild it from scratch, like a few other sandboxie mechanics btw...

**Comment by lmou523** [comment]
> The way this works seams intentional, see Scm_GetAllServices it check if the first letter of a service name is '*' and skips it. also Scm_DeleteService does not remove the actual reg key for the service.
> 
> As I wrote the Sandboxie+ Roadmap the entire sandboxed SCM mechanism needs to gets reworked, best would be to rebuild it from scratch, like a few other sandboxie mechanics btw...

I know what you mean, I am here to fix the registry key will not be deleted when the service is uninstalled
This will result in a new one when the software is installed again
image
Hopefully you can handle this when you refactor

**Comment by lmou523** [comment]
> The way this works seams intentional, see Scm_GetAllServices it check if the first letter of a service name is '*' and skips it. also Scm_DeleteService does not remove the actual reg key for the service.
> 
> As I wrote the Sandboxie+ Roadmap the entire sandboxed SCM mechanism needs to gets reworked, best would be to rebuild it from scratch, like a few other sandboxie mechanics btw...

I want to report a problem to you. I know it is not in accordance with the specification, but I put it in the issue so you can't see it
When I start a cmd in the sandbox, its command line result, proc_createprocessinternalw, is later changed, causing problems

This is my test code and binary
image
[CreateCmd.zip](https://github.com/sandboxie-plus/Sandboxie/files/11963400/CreateCmd.zip)
When I let this program execute in the sandbox, its /c is discarded（Win11）
image

**Comment by lmou523** [comment]
> > The way this works seams intentional, see Scm_GetAllServices it check if the first letter of a service name is '*' and skips it. also Scm_DeleteService does not remove the actual reg key for the service.
> > As I wrote the Sandboxie+ Roadmap the entire sandboxed SCM mechanism needs to gets reworked, best would be to rebuild it from scratch, like a few other sandboxie mechanics btw...
> 
> I want to report a problem to you. I know it is not in accordance with the specification, but I put it in the issue so you can't see it When I start a cmd in the sandbox, its command line result, proc_createprocessinternalw, is later changed, causing problems
> 
> This is my test code and binary image [CreateCmd.zip](https://github.com/sandboxie-plus/Sandboxie/files/11963400/CreateCmd.zip) When I let this program execute in the sandbox, its /c is discarded（Win11） image

image

**Comment by lmou523** [comment]
> > > The way this works seams intentional, see Scm_GetAllServices it check if the first letter of a service name is '*' and skips it. also Scm_DeleteService does not remove the actual reg key for the service.
> > > As I wrote the Sandboxie+ Roadmap the entire sandboxed SCM mechanism needs to gets reworked, best would be to rebuild it from scratch, like a few other sandboxie mechanics btw...
> > 
> > 
> > I want to report a problem to you. I know it is not in accordance with the specification, but I put it in the issue so you can't see it When I start a cmd in the sandbox, its command line result, proc_createprocessinternalw, is later changed, causing problems
> > This is my test code and binary image [CreateCmd.zip](https://github.com/sandboxie-plus/Sandboxie/files/11963400/CreateCmd.zip) When I let this program execute in the sandbox, its /c is discarded（Win11） image
> 
> image

image
image
Windows 10 call SbieDll TranslateNtToDosPath path:
image
Windows 11 call SbieDll TranslateNtToDosPath path:
image

**Comment by DavidXanatos** [comment]
fixed: https://github.com/sandboxie-plus/Sandboxie/commit/c9556e56ef26af9312618fc1e085d5abc569a44c

**Comment by lmou523** [comment]
> fixed: [c9556e5](https://github.com/sandboxie-plus/Sandboxie/commit/c9556e56ef26af9312618fc1e085d5abc569a44c)

thanks

**Pull request closed without merging**
