### PR TITLE
Clean up the invalid values that do not exist for m_Collapsed

### PR DESCRIPTION
**Pull request by okrc**
This should be the last change, it will clean up the invalid values that do not exist in m_Groups for m_Collapsed.

### CODE REVIEW

**Comment by isaak654** [comment]
#2234

**Comment by DavidXanatos** [comment]
not only groups can be collapsed but also boxes so the check must check for boxes and groups

**Comment by okrc** [comment]
It occurred to me that the QStringList stored in m_Group contains the names of the group and the box. By eliminating the non-existent values from m_Collapsed in m_Group, the check is done for both the box and the group. Am I missing anything else?

**Comment by okrc** [comment]
In fact, another omission here is used to clean up invalid Box names in m_Group.

**Pull request merged**
