### PR TITLE
Cleanup configuration

### PR DESCRIPTION
**Pull request by okrc**
Fix https://github.com/sandboxie-plus/Sandboxie/issues/2231

### CODE REVIEW

**Comment by DavidXanatos** [comment]
[c19bda4](https://github.com/sandboxie-plus/Sandboxie/pull/2234/commits/c19bda441645beec7dec4adfc9ac7cd0b0ab9ad9)
and 
[3e406dc](https://github.com/sandboxie-plus/Sandboxie/pull/2234/commits/3e406dc4eebe5643a3febbba8f322184edff7c5d)
does not seam to be needed the box object being held by a smart pointer will be available until it goes out of scope so name does not need to be cached

Explicitly deleting SizeCache entries is an improvement, but it does not handle the case where a box is deleted manually from the ini or using the old classic ui. 
It would be best to add a clean up routine here https://github.com/sandboxie-plus/Sandboxie/blob/e5d1fab9edc40608fae853abf3f26c7ba47685b7/SandboxiePlus/SandMan/SandMan.cpp#L1600
such that on start/connect once we have a list of all existing boxes we purge the size cache.

**Comment by okrc** [comment]
~~This PR doesn't do much more with SizeCache.~~
I will remove all changes to SizeCache.

> [c19bda4](https://github.com/sandboxie-plus/Sandboxie/pull/2234/commits/c19bda441645beec7dec4adfc9ac7cd0b0ab9ad9) and [3e406dc](https://github.com/sandboxie-plus/Sandboxie/pull/2234/commits/3e406dc4eebe5643a3febbba8f322184edff7c5d) does not seam to be needed the box object being held by a smart pointer will be available until it goes out of scope so name does not need to be cached
> 
> Explicitly deleting SizeCach

I don't understand here, is that [meant](https://github.com/sandboxie-plus/Sandboxie/pull/2234/commits/c19bda441645beec7dec4adfc9ac7cd0b0ab9ad9#diff-97100eacc2b039cb7dda7ed3ca92e6fb4572a58ab0a8db6c24bad0530c13a1dbL1236)?

https://github.com/sandboxie-plus/Sandboxie/pull/2234/commits/a8cdb4029593234d33d7b6d135e955369214a8cb
is an additional issue. The names are not determined and escaped for these matches.

**Comment by okrc** [comment]
> I'll add this to the next build

这里还有一些问题，关闭统计后SizeCache依旧存在，但是Value已经不再更新。

There are still some problems here, after closing Count the SizeCache still exists, but the Value is no longer updated.

**Comment by DavidXanatos** [comment]
I merged the changes and fixed a few things that did not seam right, also added an improved handling of the size cache

**Comment by isaak654** [comment]
@DavidXanatos In PRs like this one, I would advise in the next future to use the "Squash and merge" type of merging instead of the traditional "Create a merge commit":
GitHub_merge

The first one is more chaotic when there is a certain number of commits in the same PR.

**Comment by okrc** [comment]
@DavidXanatos
https://github.com/sandboxie-plus/Sandboxie/commit/52752774210f7fe168ae5a9175561430a1a82b08#
``` c++
			foreach(const QString & Key, theConf->ListKeys("SizeCache")) {
				if (!AllBoxes.contains(Key.toLower()))
					theConf->DelValue("SizeCache/" + Key);
			}
```

When the WatchBoxSize is modified, the handling should change here. For example:

``` c++
			if (theConf->GetBool("Options/WatchBoxSize", false)) {
				foreach(const QString & Key, theConf->ListKeys("SizeCache")) {
					if (!AllBoxes.contains(Key.toLower()))
						theConf->DelValue("SizeCache/" + Key);
				}
			}
			else {
				theConf->DelValue("SizeCache");
			}
```

**Comment by DavidXanatos** [comment]
I'll go with 

```
			foreach(const QString & Key, theConf->ListKeys("SizeCache")) {
				if (!AllBoxes.contains(Key.toLower()) || !theConf->GetBool("Options/WatchBoxSize", false))
					theConf->DelValue("SizeCache/" + Key);
			}
```

**Pull request merged**
