### PR TITLE
 fix miss '<' of line 1575 & a mistake of line 226.

### PR DESCRIPTION
**Pull request by Zerorigin**
fix miss '<' of `<location filename="Forms/OptionsWindow.ui" line="1575"/>`
Had a one char typo in the previous merge (sorry, didn't compile on my side before, so I didn't notice it :/)
Just had a missing <.

After review, fixed a translation mistake of `<location filename="Forms/OptionsWindow.ui" line="226"/>`.

### CODE REVIEW

**Comment by Zerorigin** [comment]
The translation of `<location filename="Forms/OptionsWindow.ui" line="1750"/>`, it doesn't seem to work.

**Comment by isaak654** [comment]
> The translation of `<location filename="Forms/OptionsWindow.ui" line="1750"/>`, it doesn't seem to work.

What do you mean exactly?

**Comment by Zerorigin** [comment]
> > The translation of `<location filename="Forms/OptionsWindow.ui" line="1750"/>`, it doesn't seem to work.
> 
> What do you mean exactly?

On SandMan UI, it still show in English.

**Comment by isaak654** [comment]
> > > The translation of `<location filename="Forms/OptionsWindow.ui" line="1750"/>`, it doesn't seem to work.
> > 
> > 
> > What do you mean exactly?
> 
> On SandMan UI, it still show in English.

The rule specificity description is translated correctly in other languages (just checked with Dutch, German and Italian), so it's something related to the characters provided in your translation.

**Pull request merged**
