### PR TITLE
Fixed bug with Rename Sandbox

### PR DESCRIPTION
**Pull request by okrc**
Fixed https://github.com/sandboxie-plus/Sandboxie/issues/2357

### CODE REVIEW

**Comment by isaak654** [comment]
@okrc Can you confirm it was fixed in https://github.com/sandboxie-plus/Sandboxie/actions/runs/3274939738 ?
Note: this is a test branch.

**Comment by okrc** [comment]
``` cmd
   set qtPath=%~dp0..\..\Qt\5.15.2\msvc2019_64 
 REM  set qtPath=%~dp0..\..\Qt\6.3.1\msvc2019_64 
```
@isaak654 I don't think it should be changed that way. Just uncomment 6.3.1 and re-comment 5.15.2.

**Comment by isaak654** [comment]
@okrc Fixed with https://github.com/sandboxie-plus/Sandboxie/commit/a048037134f91f6ea1f21833192a47d81dee3382

**Comment by isaak654** [comment]
I think there is still something wrong in the [build process](https://github.com/sandboxie-plus/Sandboxie/actions/runs/3275127382/jobs/5389570889), there is always some `The system cannot find the file specified.` 🤔

**Pull request merged**
