### PR TITLE
Korean.isl - Update encoding

### PR DESCRIPTION
**Pull request by VenusGirl**
Changing the encoding because there was a problem with Korean not being displayed properly when installation

샌드박스 설치

### CODE REVIEW

**Comment by isaak654** [comment]
Fair enough, but the line ending should be the same of the other .isl files (LF).

**Comment by isaak654** [comment]
I think this should be properly tested by @DavidXanatos before merging, otherwise we risk running in circles.

**Comment by DavidXanatos** [comment]
if this looks right: 
grafik


then the PR can be merged

**Comment by VenusGirl** [comment]
Now I can see the Korean language correctly.

**Comment by DavidXanatos** [comment]
I just saw the current 1.3.2 installer is missing the fix, a new one will be provided soon

**Comment by DavidXanatos** [comment]
fixed installer uploaded please test

**Comment by VenusGirl** [comment]
sandInstall01
sandinstall02

All are now well displayed when you install it.

**Pull request merged**
