### PR TITLE
Update sandman_sv_SE.ts

### PR DESCRIPTION
**Pull request by Thatagata**
Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option. 

In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

### CODE REVIEW

**Comment by Thatagata** [comment]
So, isaak, now then?!

**Comment by isaak654** [comment]
#3243

**Comment by isaak654** [comment]
> All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

Specifically:

> You shouldn't ever edit the text inside the source tags of the .ts file(s) before applying the same change on the respective source code file(s). 

But even if you edit the source code file, I think it could be rejected anyway. I'm under the impression that the new lines you're trying to remove were consciously introduced by @DavidXanatos to create a space between the two sentences.

**Comment by Thatagata** [comment]
Yes, got it. I made a mistake there.

Per


Den Sun, 27 Aug 2023 09:32:46 -0700, isaak654 ***@***.***> skrev:
 
 


All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19


Specifically:


You shouldn't ever edit the text inside the source tags of the .ts file(s) before applying the same change on the respective source code file(s).


But even if you edit the source code file, I think it could be rejected anyway. I'm under the impression that the new lines you're trying to remove were consciously introduced by @DavidXanatos to create a space between the two sentences.

**Comment by DavidXanatos** [comment]
i jsut fixed XML formating 2 tags were spliced into each other

**Comment by Thatagata** [comment]
I do not know what this means but, good - ok.


Per


Den Sun, 27 Aug 2023 10:46:07 -0700, DavidXanatos ***@***.***> skrev:
 
 

i jsut fixed XML formating 2 tags were spliced into each other

**Pull request closed without merging**
