### PR TITLE
Improve deletion of leftovers

### PR DESCRIPTION
**Pull request by isaak654**
This pull request improves deletion of some entries left by Sandboxie Plus.

### CODE REVIEW

**Comment by offhub** [comment]
> No tests were carried out on these changes

```
Error on line 649 in Sandboxie-Plus_modified.iss: Column 13:
Unknown identifier 'IsUserAnAdmin'
Compile aborted.
```

> as I do not know how to generate a test installer for Sandboxie Plus (see the unfinished instructions for [Installer/ReadMe.md](https://github.com/sandboxie-plus/Sandboxie/blob/5c9fdbfc4e493ce70e1bfc05f3b2619fdbe02241/Installer/ReadMe.md)).

Try this script:

```bat
@echo off
setlocal enabledelayedexpansion

where curl >nul 2>nul
if %errorlevel% neq 0 (
    echo ERROR: curl is not installed or not in the system PATH.
    echo Please install curl or ensure it is available in the system PATH.
    exit /b
)

where tar >nul 2>nul
if %errorlevel% neq 0 (
    echo ERROR: tar is not installed or not in the system PATH.
    echo Please install tar or ensure it is available in the system PATH.
    exit /b
)

:: Ask the user for confirmation before proceeding
echo.
echo =====================================================
echo This script will:
echo 1. Download the Sandboxie source code from GitHub. ~8 MB
echo 2. Download the Sandboxie installer from GitHub. ~21 MB
echo 3. Download the Inno Setup installer from jrsoftware.org. ~6 MB
echo 4. Extract all files. ~44 MB
echo 5. Remove the SignTool line from the Inno Setup script.
echo 6. Compile the installer. ~21 MB
echo.
echo You can run this script within a Sandbox for added security.
echo =====================================================
echo.
set /p userInput="Do you want to continue? (Y/N): "

if /i "%userInput%" neq "Y" (
    echo Script aborted by user.
    exit /b
)

:: Compile settings
set "compileDir=sbiePlusInnoCompileDir"
set "compilePath=%TEMP%\sbiePlusInnoCompileDir"

:: Branch settings
set "repoUrl=https://github.com/sandboxie-plus/Sandboxie/archive/refs/heads"
set "brachName=master"
set "brachSourceFile=%brachName%.zip"
set "brachSourceOut=Sandboxie-%brachName%.zip"

:: Inno Setup settings
set "innoUrl=https://jrsoftware.org/download.php/is.exe"
set "innoOut=innosetup.exe"
set "innoDir=%innoOut:~0,-4%"

:: Sandboxie-Plus settings
set "sbiePlusUrl=https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.15.1/Sandboxie-Plus-x64-v1.15.1.exe"
set "sbiePlusOut=Sandboxie-Plus.exe"
set "sbiePlusDir=%sbiePlusOut:~0,-4%"
set "sbiePlusPath=%compilePath%\Sandboxie-%brachName%\Installer\Release\%sbiePlusDir%"

:: Inno Setup Command-Line Compiler settings
set "SbiePlusVer=1.15.2.99"
set "SbiePlusArch=x64"
set "SbiePlusSrc=%sbiePlusDir%"

:: Change to the TEMP directory
cd /d "%TEMP%" && md "%compileDir%" & cd /d "%compilePath%"

pushd "%cd%"

:: Check if the branch source zip file exists
if not exist "%brachSourceOut%" (
    :: Download the ZIP file from GitHub
    curl --fail -L "%repoUrl%/%brachSourceFile%" -o "%brachSourceOut%"
    
    :: Check if the download was successful
    if %errorlevel% equ 0 (
        :: Extract the downloaded ZIP file
        tar -xf "%brachSourceOut%" -C "%compilePath%"
        echo Extraction complete.
    ) else (
        echo Failed to download the ZIP file.
    )
) else (
    echo Branch source file already exists: %brachSourceOut% ^(Extracting...^)
    :: If the file exists, extract it again
    tar -xf "%brachSourceOut%" -C "%compilePath%"
    echo Extraction complete.
)

:: Set input and output file paths
set "ISS_INPUT_FILE=%compilePath%\Sandboxie-%brachName%\Installer\Sandboxie-Plus.iss"
set "ISS_OUTPUT_FILE=%compilePath%\Sandboxie-%brachName%\Installer\Sandboxie-Plus_modified.iss"

:: Remove the SignTool line
type %ISS_INPUT_FILE% | find /v /i "SignTool" > %ISS_OUTPUT_FILE%

echo Line removed successfully.

:: Check if the Inno Setup installer already exists
if not exist "%innoOut%" (
    :: Download the Inno Setup file from jrsoftware.org
    curl --fail -L "%innoUrl%" -o "%innoOut%"
    
    :: Check if the download was successful
    if %errorlevel% equ 0 (
        :: Extract the downloaded EXE file
        %innoOut% /portable=1 /verysilent /currentuser "/dir=%compilePath%\%innoDir%"
        echo Extraction complete.
    ) else (
        echo Failed to download the EXE file.
    )
) else (
    echo Inno Setup installer already exists: %innoOut% ^(Extracting...^)
    :: If the file exists, extract it again
    %innoOut% /portable=1 /verysilent /currentuser "/dir=%compilePath%\%innoDir%"
    echo Extraction complete.
)

:: Check if the Sandboxie-Plus executable already exists
if not exist "%sbiePlusOut%" (
    :: Download the Sandboxie-Plus file from GitHub
    curl --fail -L "%sbiePlusUrl%" -o "%sbiePlusOut%"
    
    :: Check if the download was successful
    if %errorlevel% equ 0 (
        :: Extract the downloaded EXE file
        %sbiePlusOut% /portable=1 /verysilent /currentuser "/dir=%sbiePlusPath%"
        echo Extraction complete.
    ) else (
        echo Failed to download the EXE file.
    )
) else (
    echo Sandboxie-Plus installer already exists: %sbiePlusOut% ^(Extracting...^)
    :: If the file exists, extract it again
    %sbiePlusOut% /portable=1 /verysilent /currentuser "/dir=%sbiePlusPath%"
    echo Extraction complete.
)

:: Ask the user for confirmation before starting the compilation process
echo.
echo =====================================================
echo You are about to start the compilation of the installer.
echo This will compile the Sandboxie-Plus installer using
echo the modified Inno Setup script.
echo =====================================================
echo.
set /p userInput="Do you want to continue with the compilation? (Y/N): "

if /i "%userInput%" neq "Y" (
    echo Compilation aborted by user.
    exit /b
)

:: Compile the installer
%compilePath%\%innoDir%\ISCC.exe /O"%compilePath%" "%ISS_OUTPUT_FILE%" /DMyAppVersion=%SbiePlusVer% /DMyAppArch=%SbiePlusArch% /DMyAppSrc=%SbiePlusSrc%

:: Ask the user if they want to open the TEMP folder after compilation
echo.
echo =====================================================
echo Compilation is complete.
echo You can now find the compiled installer in the TEMP folder.
echo =====================================================
echo.
set /p userInput="Do you want to open the TEMP folder now? (Y/N): "

if /i "%userInput%" equ "Y" (
    echo Opening TEMP folder...
    start explorer "%compilePath%"
) else (
    echo TEMP folder not opened.
)

pause
```

**Comment by isaak654** [comment]
I have solved the compiler issues, but I can't get to work the following part to delete any registry key containing a certain value:
https://github.com/sandboxie-plus/Sandboxie/blob/f550ab90ee705c456daef253d529762071e4d37b/Installer/Sandboxie-Plus.iss#L659-L703

File/directory deletion works fine with https://github.com/sandboxie-plus/Sandboxie/pull/4374/commits/e41b3bb833f687d483e3ee95f6895d27b0706c56, so no reason to add extra code.

**Comment by isaak654** [comment]
I have solved the compiler issues, but I can't get to work the following part to delete any registry value containing a certain word from a list of registry keys:
https://github.com/sandboxie-plus/Sandboxie/blob/f550ab90ee705c456daef253d529762071e4d37b/Installer/Sandboxie-Plus.iss#L659-L703

File/directory deletion works fine with https://github.com/sandboxie-plus/Sandboxie/pull/4374/commits/e41b3bb833f687d483e3ee95f6895d27b0706c56, so no reason to add extra code.

**Comment by isaak654** [comment]
> I can't get to work the following part to delete any registry value containing a certain word from a list of registry keys

If there are no new contributions in this regard, my plan is to merge the modifications to [UninstallDelete] that work well and that I have tested.

**Comment by offhub** [comment]
I don't think it's necessary to delete keys that were not created by Sandboxie. Perhaps an addition could be made to delete the Xanasoft key if it's empty.

**Comment by offhub** [comment]
We should delete the `SOFTWARE\Xanasoft\Sandboxie-Plus` key first, as it contains the configuration data for the context menu and other integration features. This can be done using the uninstaller script or the `CSbieUtils::RemoveContextMenu()` function. After that, we can remove the parent `SOFTWARE\Xanasoft` key, which may remain but is no longer needed once the program’s core integration and features are removed.

**Comment by DavidXanatos** [comment]
We should not use CSbieUtils::RemoveContextMenu() to clear SOFTWARE\Xanasoft\Sandboxie-Plus that should be done by teh script, also we should check if SOFTWARE\Xanasoft is empty as in future other software may use that key as well

**Comment by isaak654** [comment]
Please review latest changes in this PR.

**Review by offhub — APPROVED** [review]

**Review by DavidXanatos — APPROVED** [review]
looks good

**Pull request merged**
