### PR TITLE
Properly fix Lingerer Templates, switch to UTF-8 files

### PR DESCRIPTION
**Pull request by stdedos**
* Fix comments in https://github.com/sandboxie-plus/Sandboxie/pull/534#issuecomment-775982313
* Switch Templates.ini file to UTF-8 (for better integration with git)

Fixes: #499, #541

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

### CODE REVIEW

**Comment by stdedos** [comment]
@DavidXanatos I haven't found where Sandboxie.ini is been created as UTF-8 😕

**Comment by DavidXanatos** [comment]
> 
> 
> @DavidXanatos I haven't found where Sandboxie.ini is been created as UTF-8 😕

It uses the last encoding encountered, so stop the driver open the file wherever you have it (win dir or driver dir) save it as UTF8 restart the driver and voila it than should save the file in that format in future

**Comment by stdedos** [comment]
Oh ... but we cannot change it in-code, so that it is saved as UTF-8?

**Comment by stdedos** [comment]
> * Switch Templates.ini file to UTF-8 (for better integration with git)

btw, I guess I missed it. DISCLAIMER:
> I haven't tested the change vigorously, but it has been sitting on my desktop for a couple of weeks already.

**Comment by DavidXanatos** [comment]
The driver should auto detect the file encoding and act accordingly

**Comment by DavidXanatos** [comment]
the file seams not to work ok

**Comment by isaak654** [comment]
> 
> 
> the file seams not to work ok

@DavidXanatos 
Could you be more specific? What happened to revert the old encoding (curiosity)?

**Comment by DavidXanatos** [comment]
the coments were wrong it should have been #

**Comment by isaak654** [comment]
> 
> 
> the coments were wrong it should have been #

It's UTF-8 now, thank you.

**Pull request merged**
