### PR TITLE
Changed the message notification for system color change.

### PR DESCRIPTION
**Pull request by okrc**

### CODE REVIEW

**Comment by isaak654** [comment]
Out of curiosity - if David agrees, would you be available to become a collaborator in this repository?

**Comment by okrc** [comment]
> Out of curiosity - if David agrees, would you be available to become a collaborator in this repository?

I'm sorry because my English is very poor and this may make some work very inefficient. I can only try to spend some time to make some improvements.

**Comment by DavidXanatos** [comment]
does this message works for you? currently i don't hit that code no mater if the old or new message is monitored when i change the system preset for dark theme

**Comment by okrc** [comment]
> currently i don't hit that code no mater if the old or new message is monitored when i change the system preset for dark theme

From the result of the translation, I don't understand the meaning of this sentence.

The old message actually only monitored the change in system theme color, i.e.
image
The new message is working on my Windows 11. It can handle dark and light color changes.

**Comment by okrc** [comment]
Sorry, I tested Windows 10 and it didn't work. I should probably try WM_SETTINGCHANGE, which is used by some other projects.

**Comment by DavidXanatos** [comment]
This seams to work with color 
how about we just monitor WM_SETTINGCHANGE that one seams to work just fine

**Pull request merged**
