### PR TITLE
Fixed German spelling for Text-German-1031.txt

### PR DESCRIPTION
**Pull request by NewKidOnTheBlock**
There was a warning message though:
"We’ve detected the file encoding as UTF-16LE. When you commit changes we will transcode it to UTF-8."

### CODE REVIEW

**Comment by isaak654** [comment]
> There was a warning message though:
> "We’ve detected the file encoding as UTF-16LE. When you commit changes we will transcode it to UTF-8."

It means that this commit is broken, and if it will be merged (as it is now), it will break the german translation too.

It happened to me as well:
https://github.com/sandboxie-plus/Sandboxie/pull/264

**Comment by NewKidOnTheBlock** [comment]
I can't find a way to switch Notepad++ to UTF16 LE...
Closing.

**Comment by NewKidOnTheBlock** [comment]
Okay, I have no clue how this is supposed to work.
The second I click the edit button, Github notifies me that it's gonna destroy the coding by converting it from UTF16LE to UTF8.
And there's no other way to edit the file.

**Comment by DavidXanatos** [comment]
Download it on your HDD use a tool like Tortois SVN edit it locally and commit the changes

**Comment by isaak654** [comment]
> 
> 
> I can't find a way to switch Notepad++ to UTF16 LE.
> Closing.

@NewKidOnTheBlock 
In Notepad++, UTF16 LE is UCS-2 LE BOM. You should keep that encoding without changing it.

These are the complete steps to follow:
1) You should download the file you want from the repo to edit it locally in your pc
2) Use Notepad++ to perform the changes (keeping the odd UCS-2 LE BOM encoding)
3) Create a fork, go to the path where you want to update the file (i.e. [here](https://github.com/isaak654/Sandboxie/tree/master/Sandboxie/msgs)) and upload the translated file there using the "Add file" -> "Upload files" function (see my attachment). In this way you will bypass the online editor conversion.
4) Choose your file(s) to upload on the upper screen (drag&drop doesn't work for me), put a title to your commit and select the option "Commit directly to the master branch. "
5) You will be redirected on your forked repo again. Now click on "Pull request" button (under Add file button).
6) Now you can create the pull request that will be posted directly in sandboxie-plus/Sandboxie.

image

**Comment by NewKidOnTheBlock** [comment]
@isaak654
Thanks for the detailed explanation.
I think I was able to pull it off on the umpteenth try.

I'd still say that converting all .txts to UTF-8 would make everyone's life easier.
It would also carry the benefit of being able to see the diffs directly without downloading 2 files and running the comparison manually.

**Comment by DavidXanatos** [comment]
> P.S: I'm assuming that @DavidXanatos is using a Linux distribution, and this online editor issue appears when you use the feature in a Windows OS.

No I would be using linux I would not work on tools for windows.

I just don't use  gits onlien editors but Notepad2

**Pull request closed without merging**
