### PR TITLE
Update codespell.yml

### PR DESCRIPTION
**Pull request by kokofixcomputers**
I just noticed this issue! This one should make the spell check pass

### CODE REVIEW

**Comment by isaak654** [comment]
It seems that it can be written [both ways](https://www.wordreference.com/enit/socioeconomic%20status).

Unless stated otherwise, it would probably make sense to update our [ignore words list](https://github.com/sandboxie-plus/Sandboxie/blob/da1ecf59ac05c3a6edf294e20b320b2850c8d8e4/.github/workflows/codespell.yml#L126).

**Comment by isaak654** [comment]
I'm going to mention @NewKidOnTheBlock for a possible confirmation on this.

**Comment by isaak654** [comment]
> It seems that it can be written [both ways](https://www.wordreference.com/enit/socioeconomic%20status).

I'm going to mention @NewKidOnTheBlock for further confirmation.

**Comment by kokofixcomputers** [comment]
> > It seems that it can be written [both ways](https://www.wordreference.com/enit/socioeconomic%20status).
> 
> I'm going to mention @NewKidOnTheBlock for further confirmation.

Okay

**Comment by NewKidOnTheBlock** [comment]
You summoned me?
"socio-economic" looks good.

I got a question though:
How would I know anyone's "body size" or "economic status", unless that person willfully dumped all that info here in the first place?

**Comment by isaak654** [comment]
GitHub provides a couple of standard templates as code of conduct, what I did was to choose one and adapt it.

Regarding the incorrectly reported term, I have opened the pull request https://github.com/codespell-project/codespell/pull/3353 in the codespell repository. Depending on how long it takes, I'll see whether it's worth the wait.

**Comment by kokofixcomputers** [comment]
> GitHub provides a couple of standard templates as code of conduct, what I did was to choose one and adapt it.
> 
> Regarding the incorrectly reported term, I have opened the pull request [codespell-project/codespell#3353](https://github.com/codespell-project/codespell/pull/3353) in the codespell repository. Depending on how long it takes, I'll see whether it's worth the wait.

okay! thank you!

**Pull request merged**
