### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by lufog**

### CODE REVIEW

**Comment by isaak654** [comment]
Could you translate the Plus installer too?
https://github.com/sandboxie-plus/Sandboxie/blob/f8534d56da3366d9b27a68a1b019fea45de456be/Installer/Languages.iss#L39-L54

Just in case, remember to replace `english.` with `russian.`

**Review by isaak654 — CHANGES_REQUESTED** [review]
`<byte value="xd"/>` references are required as workaround to fix a bug, see https://github.com/sandboxie-plus/Sandboxie/pull/1035#issuecomment-886118125

It is required only for some specific source tag, in the same places before your last changes.

**Comment by lufog** [comment]
> Could you translate the Plus installer too?

Ok

> `<byte value="xd"/>` references are required as workaround to fix a bug, see [#1035 (comment)](https://github.com/sandboxie-plus/Sandboxie/pull/1035#issuecomment-886118125)
> It is required only for some specific source tag, in the same places before your last changes.

This tag was automatically removed by QtLinguist, I will add it again manually.

**Comment by isaak654** [comment]
> 
> 
> This tag was automatically removed by QtLinguist, I will add it again manually.

Unfortunately I have no idea about another alternative... maybe opening a new issue could help.

**Comment by lufog** [comment]
@isaak654, I think I fixed everything.

**Comment by isaak654** [comment]
> 
> 
> I think I fixed everything.

Now you need to remove them from inside the translation tags. They are only needed for specific source tags.

**Comment by lufog** [comment]
Done

**Review by isaak654 — APPROVED** [review]

**Pull request merged**
