### PR TITLE
Request to cancel a security workaround for VMnet0

### PR DESCRIPTION
**Pull request by 0x391F**
Canceled close VMNet0 virtual network, because most users don't need it. In fact, I have to edit it manually after update sandboxie everytime to reenable it.

### CODE REVIEW

**Comment by isaak654** [comment]
VMNet0

**Comment by isaak654** [comment]
#1481

**Comment by 0x391F** [comment]
Uh, but nowadays, only normal boxes could be used, unless user have a supporter certificate, isn't it?

**Comment by isaak654** [comment]
> Uh, but nowadays, only normal boxes could be used, unless user have a supporter certificate, isn't it?

That's correct, you can only use the other boxes for 5 minutes without the certificate. For further details, see [CONTRIBUTING.md](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md).

In my opinion, [your activities](https://github.com/sandboxie-plus/Sandboxie/issues?q=author%3A0x391F) in reporting / testing issues could be compensated with a contributor certificate. If you need confirmation, please do not hesitate to contact the maintainer by email (as indicated in the first link).

**Comment by isaak654** [comment]
#1102

**Comment by isaak654** [comment]
@0x391F Please review #2498 as a possible alternative fix for your use case.

**Pull request closed without merging**
