### PR TITLE
Cleanup critical sections

### PR DESCRIPTION
**Pull request by chunyou128**
_Originally posted by the author in #1677_
I can't find a proper place to clean critical section for sbiedll.dll

### CODE REVIEW

**Review by DavidXanatos — APPROVED** [review]
I think this looks fine, I'll comment out the change in dllmain.c for now though

**Comment by isaak654** [comment]
@chunyou128 
Thank you for your valuable contribution.
If you'd like to join the Sandboxie-Plus Slack channel, you can send a request to the email listed on David's Github profile.

**Comment by DavidXanatos** [comment]
@chunyou128 and even if you may not want to join slack drop me an email to get your perpetual sandboxie certificate ;)

**Comment by chunyou128** [comment]
> @chunyou128 Thank you for your valuable contribution. If you'd like to join the Sandboxie-Plus Slack channel, you can send a request to the email listed on David's Github profile.

I have submitted the application with QQ mailbox(584002587@qq.com) and asked for approval. thanks.

**Comment by chunyou128** [comment]
> @chunyou128 and even if you may not want to join slack drop me an email to get your perpetual sandboxie certificate ;)

I am very honored  if I can get the perpetual sandboxie certificate.Thank you very much.

**Pull request merged**
