### PR TITLE
add appveyor ci build

### PR DESCRIPTION
**Pull request by ivan-kulikov-dev**

### CODE REVIEW

**Comment by ivan-kulikov-dev** [comment]
https://ci.appveyor.com/project/ivan-kulikov-dev/sandboxie/builds/32246591

**Comment by DavidXanatos** [comment]
Whats the real benefit of this solution? My current work flow is just to build it manually on a dedicated clean VM.

**Comment by ivan-kulikov-dev** [comment]
Benefits in building code when pulling a request.
Example:
изображение

**Comment by StefanScherer** [comment]
AppVeyor also supports to store build artifacts, so it would be very easy for reviewers / community to try out a PR build without having a dev environment.

**Comment by VitRom** [comment]
Very nice. Just don't forget about 2019's spring and the Matrix.org

**Comment by S0PEX** [comment]
I would also appreciate this as currently I have to spin up my vm to build sandboxie.

**Pull request closed without merging**
