### PR TITLE
Update German translation for plus version

### PR DESCRIPTION
**Pull request by bastik-1001**
Had fixed a typo before.

86d6ca6 is the one that contains all new strings and required changes. (Which is true for f724716 as well)

### CODE REVIEW

**Comment by bastik-1001** [comment]
Is there a way for me to tell when "Dismiss" means basically "Close"? I translated all instances of "Dismiss" to be the same namely being dismissive about what is shown on the screen. For some it does not appear to be correct like "Program was started outside of the sandbox" (Forced programs disabled) in which it seems to be an information and nothing that the user can negate.

**Comment by yuhao2348732** [comment]
dismiss means ignore

**Comment by DavidXanatos** [comment]
I created a slack channel for sandboxie-plus, if you send me an email address than I can send you an invite.
That would be more convenient for communication.

**Comment by bastik-1001** [comment]
@DavidXanatos I used your forum to send you the required information.

**Comment by DavidXanatos** [comment]
@bastik-1001 i did not get it, just send it on my gmail address

**Comment by DavidXanatos** [comment]
found it seam to have ended up in the spam filter, you should get a invite from slack shortly

**Pull request merged**
