### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by cricri-pingouin**
Just fixed a bunch of typos, no code changes.
Sorry about Sandman.cpp, I only changed a couple of typos in there, and the compare highlights whole sections of the code as removed/added!

### CODE REVIEW

**Comment by isaak654** [comment]
Please look at OptionsWindow.cpp, I've just noticed more typos to fix:
https://github.com/cricri-pingouin/Sandboxie/blob/12c9a497406954fd5e9d0f5864aff77863a4b1fb/SandboxiePlus/SandMan/Windows/OptionsWindow.cpp#L845
https://github.com/cricri-pingouin/Sandboxie/blob/12c9a497406954fd5e9d0f5864aff77863a4b1fb/SandboxiePlus/SandMan/Windows/OptionsWindow.cpp#L1057
https://github.com/cricri-pingouin/Sandboxie/blob/12c9a497406954fd5e9d0f5864aff77863a4b1fb/SandboxiePlus/SandMan/Windows/OptionsWindow.cpp#L1064
https://github.com/cricri-pingouin/Sandboxie/blob/12c9a497406954fd5e9d0f5864aff77863a4b1fb/SandboxiePlus/SandMan/Windows/OptionsWindow.cpp#L1907 (here add a comma after globally)

**Comment by cricri-pingouin** [comment]
Thanks @isaak654 , corrected the ones you found, and fixed few more while going through those files.

**Comment by cricri-pingouin** [comment]
@isaak654 : oopsy, I didn't realise you forked, so fixed all the typos you found in my branch manually. I didn't get a notification to merge any changes, and I'm not a Github expert, so not sure this was the right way to do it!

**Comment by isaak654** [comment]
> 
> 
> Thanks @isaak654 , corrected the ones you found, and fixed few more while going through those files.

All ok for me, one fix this too (short dash is missing):
https://git.io/JLi54

> @isaak654 : oopsy, I didn't realise you forked, so fixed all the typos you found in my branch manually. I didn't get a notification to merge any changes, and I'm not a Github expert, so not sure this was the right way to do it!

Don't worry, I made that fork just for testing purposes. I'll delete it asap.

**Comment by cricri-pingouin** [comment]
Thanks, fixed the one you pointed out, and found saome more too.
Fixed some "sellect" to "select" in the German XML translation too.

**Comment by DavidXanatos** [comment]
I created a slack channel for sandboxie-plus, if you send me an email address than I can send you an invite.
That would be more convenient for communication.

**Comment by cricri-pingouin** [comment]
Hi, my email is sli51@hotmail.com, but I don't use Slack, Twitter, Facebook, etc. Thanks!

**Pull request merged**
