### PR TITLE
Update sandman_es.ts

### PR DESCRIPTION
**Pull request by sebadamus**
New updated 1.6.7 latin-america spanish

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option. 

In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

### CODE REVIEW

**Comment by sebadamus** [comment]
Tell if anything wrong...

**Comment by isaak654** [comment]
It appears that the language file merged here is an outdated version, nothing serious happened because the [automatic sync](https://github.com/sandboxie-plus/Sandboxie/commit/e02576066bf7f08222cbe2652c6731b3b622980a#diff-6906c07339f1c5d15da22f0a5d70a62515918e376b8f0378c112031d14ee8433) made its job to restore the entries correctly.

From next time, it is recommended to use the updated sandman_es.ts file, which can be downloaded from [here](https://github.com/sandboxie-plus/Sandboxie/raw/master/SandboxiePlus/SandMan/sandman_es.ts).

**Comment by sebadamus** [comment]
Sorry, if you can explain a little more I would with pleasure continue helping translating.

The file I upload is wrong or dont have everything translated?

I took the file from https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/SandboxiePlus/SandMan/sandman_es.ts

If what I ulpload is not fully please tell me again and will check (maybe some sync backup in my computer confused me)

**Comment by isaak654** [comment]
A number of lines removed in this PR were automatically restored by the lupdate job. If you actually used the latest file version, it is also possible that something useful was mistakenly removed by hand.

**Comment by sebadamus** [comment]
> 

Sorry Issak, I am lost, have no clue how to do it right.  Please count on me when the new language translation method is avaiable.

**Pull request merged**
