### PR TITLE
A update for lang_zh_CN.json

### PR DESCRIPTION
**Pull request by Rain-Clear**
This update adds annotations to help users understand the meaning of the option text, as well as changes to some translations that may not be understood.

### CODE REVIEW

**Comment by RimacC2-EV** [comment]
This update may still not accurately summarize the exact meaning of each word, could you please give me some advice?

**Comment by isaak654** [comment]
> This update may still not accurately summarize the exact meaning of each word, could you please give me some advice?

I think you should ask the current Simplified Chinese translator @nkh0472

See also https://github.com/sandboxie-plus/Sandboxie#-translators

**Comment by nkh0472** [comment]
Please rectify all modifications related to 'shell.' 
In this context, 'shell' refers to the Windows file manager (explorer.exe), not the CLI tool. 
To clarify, it mostly involves the right-click context menu just like the SBie or 7-Zip does, and in some instances, it impacts file icons and properties like OneDrive shows the file Sync status. 

Your other changes are appreciated. Feel free to contribute further, and if you have suggestions, we welcome discussion.

**Comment by RimacC2-EV** [comment]
Thanks for the criticism! I'll revise the translation right away.

**Comment by RimacC2-EV** [comment]
I corrected the translation of "Shell" earlier based on your instructions, could you please review it again? @nkh0472

**Comment by nkh0472** [comment]
> I corrected the translation of "Shell" earlier based on your instructions, could you please review it again? @nkh0472

You can consider shortening "文件资源管理器" to "资源管理器". If you prefer not to change, that's fine with me.
I suggest this PR could be merged.

**Comment by RimacC2-EV** [comment]
Ok, I also think it seems that the "explorer" translation is better, I will change the translation later, if you have any questions, welcome to ask!

**Pull request merged**
