### PR TITLE
Update Changelog 5.50.5-5.50.6

### PR DESCRIPTION
**Pull request by NewKidOnTheBlock**
Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request". You can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

### CODE REVIEW

**Comment by NewKidOnTheBlock** [comment]
If you had told me to press the Break key on my keyboard, I would not have found it.
This might be particular to German keyboards, but I'm pretty sure it's also called Pause key on American/English ones.

**Comment by isaak654** [comment]
> 
> 
> If you had told me to press the Break key on my keyboard, I would not have found it.
> This might be particular to German keyboards, but I'm pretty sure it's also called Pause key on American/English ones.

Break is an english word, so it can be found in US layouts:
https://www.computerhope.com/jargon/b/break.htm

In some keyboards with italian layouts, I have Pausa / Interr, while in others just Pausa.

Interr is the translation of break in my language.

**Comment by NewKidOnTheBlock** [comment]
An image search revealed that US-keyboards either call it "Pause" or "Pause | Break" (= both inscriptions on the key)
On my German keyboard it's called "Pause | untbr".

**Comment by isaak654** [comment]
Pause | Break seems fine to me, it covers all the cases.

**Review by isaak654 — CHANGES_REQUESTED** [review]
Dialog is preferred instead of Dialogue, because it has a specific use in computational contexts.

**Review by isaak654 — APPROVED** [review]

**Pull request merged**
