### PR TITLE
Update sandman_zh_CN.ts

### PR DESCRIPTION
**Pull request by Rain-Clear**
This update corrects some Chinese Simplified Chinese translations that may cause misunderstandings (some of which use machine translation)

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option. 

In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

### CODE REVIEW

**Comment by RimacC2-EV** [comment]
Is anybody here?

**Review by nkh0472 — COMMENTED** [review]
Looks pretty good :)

**Comment by RimacC2-EV** [comment]
> Looks pretty good :)
Thanks, that's nice

**Comment by RimacC2-EV** [comment]
> @isaak654 Could you review my pull request?

**Pull request merged**
