### PR TITLE
Improve progress and status messages

### PR DESCRIPTION
**Pull request by mpheath**
An improvement with progress messages for the Plus installer. The current uninstall is not very informative. The *KmdUtil scandll* and *KmdUtil stop SbieDrv* can each take several seconds. Looking at *Uninstalling Sandboxie-Plus...* the whole time is not progress, as it is unknown what it is doing with *KmdUtil* in the code section.

The uninstall progress messages are now informative and if something freezes for some reason, like it is paused on *KmdUtil scandll* for an hour, then you can know what is causing it by the progress message. Not that I expect that scenerio, though unexpected things can happen.

The upgrade shows a custom progress page that looks like the *Prepare To Install* page as I cannot do status messages on the *Ready* page about stopping processes, the service and the driver. Command line messages are used so no translation should be needed.

**Summary**:

 * Better progress messages for install, upgrade and uninstall.
 * Two empty lines between sections to improve readability.
 * Removed old commented sections and entries.
 * Code cleanup:
   * Moved some file deletes, registry entries and *KmdUtil* calls into the *UninstallDelete*, *Registry* and *Run* sections.
   * All keywords lowercase except for *True* and *False*.
   * Variable, function and procedure names as CamelCase.
   * Comments as Sentence case.
   * Moved any comments into definitions that were above the definitions.
   * Functions and procedures ordered with events nearest to bottom and others above.
   * Two empty lines between functions and procedures to improve readability.
   * Removed unneeded *NextButtonClick2()* and moved code into *NextButtonClick()*.
   * Removed unneeded *CurStepChanged()* and *InitializeUninstall()*.
   * Removed old commented code.
   * Removed unused variable names.

This is the [alternative script](http://users.tpg.com.au/mpheath/sandboxie/) tested for the past month ... without the *UninstallCleanup()* procedure.

Commit may put PR #1058 into conflict. That can be resolved ... or if needed, closed and post a new PR for the *UninstallCleanup()*.

Would like to discuss any concerns before a commit.

### CODE REVIEW

**Comment by isaak654** [comment]
Personally I would like to merge this PR soon after 0.9.6, resolve the conflicts in PR #1058 and split both UninstallTaskLabel5 and /RemoveSandboxes parts in a new PR with David as assignee.

**Comment by isaak654** [comment]
Personally I would suggest to merge this PR soon after 0.9.6, resolve the conflicts in PR #1058 and split both UninstallTaskLabel5 and /RemoveSandboxes parts in a new PR with David as assignee.

**Comment by mpheath** [comment]
> Personally I would suggest to merge this PR soon after 0.9.6,

Seems reasonable to commit at start of a new version development cycle. I do not want to shock anyone which is why I posted some links earlier to notify of the incoming change. Much of the proven to work code is still intact. It is the changing of case and the reorder of functions which may make the diff look like is something totally different. Any new code changes or other changes has been tested many times.

> resolve the conflicts in PR 1058

Just noticed it has already gone into conflict over `Installer/Languages.iss`.

PR 1058 can be updated later based on the commit of this PR. This will resolve conflicts.

> split both UninstallTaskLabel5 and /RemoveSandboxes parts in a new PR

Doubt if a split will help with progress, unless you imply that PR 1058 should try being like Classic with just remove of configuration files. And perhaps later, add the remove of sandboxes if still considered as worthwhile. Is this what your suggestion is about? Otherwise, I thought it was settled.

**Comment by DavidXanatos** [comment]
I pan to repease 0.9.6 this weekend, do you think i can merge this pull request and use the new script already?

**Comment by mpheath** [comment]
I consider it ready. I can let you know if the merge looks good with testing the script to undoubtly ensure it is good.

**Comment by isaak654** [comment]
> 
> Doubt if a split will help with progress, unless you imply that PR 1058 should try being like Classic with just remove of configuration files. And perhaps later, add the remove of sandboxes if still considered as worthwhile. Is this what your suggestion is about?

There is no ETA about the new /RemoveSandboxes switch, so it could be reasonable to delay it by splitting that part into a new smaller PR and merging the rest.

**Comment by mpheath** [comment]
I will change the uninstall in PR 1058 to omit `/RemoveSandboxes` later.

**Comment by isaak654** [comment]
Build 0.9.6 is out, are you ready to merge this?

I've just rerun the CIs that belong to your pull requests and it appears a WDK version mismatch.
I think it's the same for all pull requests in this section created before [this commit](https://github.com/sandboxie-plus/Sandboxie/commit/ce2627d8ddbb9c19de973e1c2eb3b344835f36cd), so I wouldn't be worry about it.

**Pull request merged**
