### PR TITLE
Various build fixes

### PR DESCRIPTION
**Pull request by isaak654**
This should fix multiple warnings: `The system cannot find the file specified.`

### CODE REVIEW

**Comment by isaak654** [comment]
> https://github.com/sandboxie-plus/Sandboxie/actions/runs/3275337877/jobs/5390053631#step:16:1
> The arm64 does not generate msix files.

I think it's the only remaining issue, but I'm not sure why:
https://github.com/sandboxie-plus/Sandboxie/blob/844fd3425b35c6ed91f820cd3fc0cd64b63772de/Installer/copy_build.cmd#L135-L153

```
2022-10-18T18:17:14.9897532Z D:\a\Sandboxie\Sandboxie>IF ARM64 == ARM64 (
2022-10-18T18:17:14.9898152Z mkdir D:\a\Sandboxie\Sandboxie\Installer\\SbiePlus_a64\32\  
2022-10-18T18:17:14.9898782Z  copy /y D:\a\Sandboxie\Sandboxie\Installer\..\Sandboxie\Bin\Win32\SbieRelease\SbieSvc.exe D:\a\Sandboxie\Sandboxie\Installer\\SbiePlus_a64\32\  
2022-10-18T18:17:14.9899449Z  copy /y D:\a\Sandboxie\Sandboxie\Installer\..\Sandboxie\Bin\Win32\SbieRelease\SbieDll.dll D:\a\Sandboxie\Sandboxie\Installer\\SbiePlus_a64\32\  
2022-10-18T18:17:14.9899952Z  mkdir D:\a\Sandboxie\Sandboxie\Installer\\SbiePlus_a64\64\  
2022-10-18T18:17:14.9900679Z  copy /y D:\a\Sandboxie\Sandboxie\Installer\..\Sandboxie\Bin\ARM64EC\SbieRelease\SbieDll.dll D:\a\Sandboxie\Sandboxie\Installer\\SbiePlus_a64\64\  
2022-10-18T18:17:14.9901397Z  copy /y D:\a\Sandboxie\Sandboxie\Installer\..\SandboxiePlus\ARM64\Release\SbieShellExt.dll D:\a\Sandboxie\Sandboxie\Installer\\SbiePlus_a64\  
2022-10-18T18:17:14.9902086Z  copy /y D:\a\Sandboxie\Sandboxie\Installer\..\SandboxiePlus\ARM64\Release\SbieShellPkg.msix D:\a\Sandboxie\Sandboxie\Installer\\SbiePlus_a64\ 
2022-10-18T18:17:14.9902578Z ) 
2022-10-18T18:17:14.9909964Z         1 file(s) copied.
2022-10-18T18:17:14.9921784Z         1 file(s) copied.
2022-10-18T18:17:14.9960341Z         1 file(s) copied.
2022-10-18T18:17:14.9968810Z         1 file(s) copied.
2022-10-18T18:17:14.9971502Z The system cannot find the file specified.
```

**Comment by okrc** [comment]
About this, again, I'm not sure why. Here I found something very strange. The manifest file is included in the SbieShell project, but it doesn't participate in the generation. I can't debug it because I'm missing certificate signatures. Even with a trusted self-signed certificate, it won't install.

**Comment by isaak654** [comment]
Personally I would leave the remaining issue to @DavidXanatos and in the meantime I could merge the current changes.

**Comment by okrc** [comment]
Here is not a simple copy, note the change between x86 and ARM64

**Comment by okrc** [comment]
https://github.com/sandboxie-plus/Sandboxie/blob/22ad296ecd8be28eaf4b9208c1dd416282c58ed2/SandboxiePlus/SbieShell/SbieShellExt/SbieShellExt.vcxproj#L305

Debug and Release, you have only modified Debug.

**Comment by okrc** [comment]
Hm, https://github.com/sandboxie-plus/Sandboxie/actions/runs/3276406740/jobs/5392420623#step:16:50
makeappx.exe not found.

As you can see from the Microsoft [documentation](https://learn.microsoft.com/windows/msix/package/create-app-package-with-makeappx-tool#using-makeappxexe), the path is correct. 
I think we can only annotate this code for now, and maybe create it for ARM64 only after upgrading the SDK version in the future.

**Comment by isaak654** [comment]
> Hm, https://github.com/sandboxie-plus/Sandboxie/actions/runs/3276406740/jobs/5392420623#step:16:50 makeappx.exe not found.
> 
> As you can see from the Microsoft [documentation](https://learn.microsoft.com/windows/msix/package/create-app-package-with-makeappx-tool#using-makeappxexe), the path is correct. I think we can only annotate this code for now, and maybe create it for ARM64 only after upgrading the SDK version in the future.

Ok, then I'm going back to the original plan: https://github.com/sandboxie-plus/Sandboxie/pull/2359#issuecomment-1282858052

**Comment by okrc** [comment]
https://github.com/sandboxie-plus/Sandboxie/blob/ce78c287ac17fefdd531dde23d487a03636f6051/SandboxiePlus/SandMan/Windows/SettingsWindow.cpp#L450-L469
Regarding the Arm64 version, I'm not sure if there is a special build of SbieShellPkg.msix, since I don't have an Arm device. If not, then the Windows 11 Arm64 device cannot add Sandman to the context menu.

**Pull request merged**
