### PR TITLE
Update Text-TradChinese-1028.txt

### PR DESCRIPTION
**Pull request by Hulen**
Update Text-TradChinese-1028.txt

### CODE REVIEW

**Comment by Hulen** [comment]
I use WinMerge to compare English and Chinese Traditional archives for collation.

Maybe too many string.

**Comment by isaak654** [comment]
The Korean translation file is slightly larger, so the Parse script is not able to process too many changes at the same time.
I would suggest to remove the commented out lines, but if you really want to restore them later, you could re-add them in different pull requests.

**Comment by isaak654** [comment]
The Korean translation file is slightly larger, so the Parse script is not able to process too many changes at the same time.
I would suggest to remove the commented out lines introduced in this pull request, but if you really want to restore them later, you could re-add them in different pull requests.

**Comment by Hulen** [comment]
OK

**Pull request closed without merging**
