### PR TITLE
Close VMNet0 only for vmnetcfg.exe

### PR DESCRIPTION
**Pull request by isaak654**
For further details, see the two references below.

### CODE REVIEW

**Comment by isaak654** [comment]
#1102

**Comment by isaak654** [comment]
@0x391F 
Please apply the change provided in this PR as a possible alternative fix for your [use case](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-993016787) and report here if it works for you.

**Comment by 0x391F** [comment]
> @0x391F Please apply the change provided in this PR as a possible alternative fix for your [use case](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-993016787) and report here if it works for you.

It seems doesn't work. I had been test: 
`ClosedFilePath=!vmware.exe,\Device\VMnetUserif `

`ClosedFilePath=!vmware.exe,\Device\VMnetUserif
ClosedFilePath=!vmware-vmx.exe,\Device\VMnetUserif`

`ClosedFilePath=!vmware.exe,\Device\VMnetUserif
ClosedFilePath=!vmware-vmx.exe,\Device\VMnetUserif
ClosedFilePath=!vmnetUserif.sys,\Device\VMnetUserif`

`ClosedFilePath=!vmware.exe,\Device\VMnetUserif
ClosedFilePath=!vmware-vmx.exe,\Device\VMnetUserif
ClosedFilePath=!vmnetcfg.exe,\Device\VMnetUserif
ClosedFilePath=!vmnetUserif.sys,\Device\VMnetUserif
ClosedFilePath=!vmnetBridge.dll,\Device\VMnetUserif
ClosedFilePath=!vmnetBridge.sys,\Device\VMnetUserif
ClosedFilePath=!vmnetAdapter.sys,\Device\VMnetUserif
ClosedFilePath=!vmnet.sys,\Device\VMnetUserif`

unfortunately, they are all useless, but once I only annotate ClosedFilePath=!vmware.exe,\Device\VMnetUserif, it works.

**Comment by isaak654** [comment]
@0x391F In case you want to exclude multiple files, please try replacing `ClosedFilePath=!vmware.exe,\Device\VMnetUserif` from Templates.ini with:
```
ProcessGroup=<VMware>,vmware.exe,vmware-vmx.exe,vmnetUserif.sys
ClosedFilePath=!<VMware>,\Device\VMnetUserif
```

Feel free to add more files in ProcessGroup (separated by comma) as second attempt.

**Comment by isaak654** [comment]
@0x391F In case you want to exclude multiple files, please try replacing `ClosedFilePath=!vmware.exe,\Device\VMnetUserif` from Templates.ini with:
```
ProcessGroup=<VMware>,vmware.exe,vmware-vmx.exe,vmnetUserif.sys
ClosedFilePath=!<VMware>,\Device\VMnetUserif
```
1. Make sure there is no `ClosedFilePath=\Device\VMnetUserif` or `ClosedFilePath=!vmware.exe,\Device\VMnetUserif` already defined in Templates.ini.
2. Feel free to add more files in ProcessGroup (separated by comma) as second attempt.

**Comment by isaak654** [comment]
@0x391F In case you want to exclude multiple files, please try using in Templates.ini:
```
ProcessGroup=<VMware>,vmware.exe,vmware-vmx.exe
ClosedFilePath=!<VMware>,\Device\VMnetUserif
```
1. Make sure there is no `ClosedFilePath=\Device\VMnetUserif` or `ClosedFilePath=!vmware.exe,\Device\VMnetUserif` already defined in Templates.ini.
2. Share a full list of processes that are opened during your use of VMware. For this, I would recommend [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) instead of the Windows one.
3. Feel free to add more .exe files in ProcessGroup (separated by comma) as second attempt.
4. You may want to use the trace log feature to track the closed VMware processes. As general reference, see [Sandboxie Plus, Resource Access Monitor, how to](https://www.youtube.com/watch?v=4k2XoT7VQuc).
5. I have no further ideas at this time.

**Comment by 0x391F** [comment]
After a serial tests, I found that only allow vmware-vmx.exe and vmnetcfg.exe works: 
`ProcessGroup=<VMware>,vmware-vmx.exe,vmnetcfg.exe
ClosedFilePath=!<VMware>,\Device\VMnetUserif`

**Comment by isaak654** [comment]
@0x391F 
As far as I know, allowing vmnetcfg.exe in Sandboxie would still write the network change outside the sandbox (#1102). Am I missing some detail for which you need to always start vmnetcfg.exe in the sandbox instead to perform the change in the real system? I would like to know more about this aspect.

**Comment by 0x391F** [comment]
> As far as I know, allowing vmnetcfg.exe in Sandboxie would still write the network change outside the sandbox (#1102). 

Unfortunately, yes.

> Am I missing some detail for which you need to always start vmnetcfg.exe in the sandbox instead to perform the change in the real system? I would like to know more about this aspect.

No, it isn't, I rarely do that. If sandboxie couldn't avoid the change affect the real system when modifying virtual network settings, I just need to revert it manually. I think compare with it, VMNet0(Bridging network) could't work is even worse.

**Comment by isaak654** [comment]
> No, it isn't, I rarely do that. If sandboxie couldn't avoid the change affect the real system when modifying virtual network settings, it just a little defect. I just need to revert it manually.

If it's rare for you to use vmnetcfg.exe, then I'm going to replace the current rule with `ClosedFilePath=!vmware-vmx.exe,\Device\VMnetUserif`. If there are no further remarks to be made, this change will be merged within a few days.

**Comment by isaak654** [comment]
On a second thought, I think I'll simply introduce `ClosedFilePath=vmnetcfg.exe,\Device\VMnetUserif` instead of that exclusion mess.

**Comment by 0x391F** [comment]
In fact, I think below settings is better: 
`ProcessGroup=<VMware>,vmware-vmx.exe,vmnetcfg.exe
ClosedFilePath=!<VMware>,\Device\VMnetUserif`
The reason why I suggest also allow vmnetcfg.exe visit \Device\VMnetUserif is: modifying virtual network settings by virtual network editor isn't a safety risk, If sandbox couldn't revert the changes on it, allow is better than deny. This rule only allow VMWare itself to use/modify \Device\VMnetUserif, which has been safer than doing nothing.

**Comment by isaak654** [comment]
[Here](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-1004026992) it was called a general flaw in the Sandboxie security architecture.

Although this can be currently remedied by manually enabling device isolation [checkbox](https://github.com/sandboxie-plus/Sandboxie/pull/1481#issuecomment-1253320292), a supporter certificate is still required and not everyone wants it.

The only thing I can adjust for your [use case](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-993016787) consists to limit the existing restriction only for the VMware tool that writes the change instead of closing completely the virtual network access to your VM.

It is inconceivable that Sandboxie cannot retain a virtual device within standard sandboxes by default, but this is the reality and I do not have the technical knowledge to do so.

**Comment by isaak654** [comment]
[Here](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-1004026992) it was called a general flaw in the Sandboxie security architecture.

Although this can be currently remedied by manually enabling device isolation [checkbox](https://github.com/sandboxie-plus/Sandboxie/pull/1481#issuecomment-1253320292), a supporter certificate is still required and not everyone wants it.

The only thing I can adjust for your [use case](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-993016787) consists to limit the existing restriction only for the VMware tool that writes the change instead of closing completely the virtual network access to your VM.

It is inconceivable that Sandboxie cannot retain a virtual device within standard sandboxes by default, but this is the reality and I do not have the technical knowledge to do so.

Also, I'm against introducing a custom template that could hide the attention to a serious issue not completely fixed.

**Comment by isaak654** [comment]
[Here](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-1004026992) it was called a general flaw in the Sandboxie security architecture.

Although this can be currently remedied by manually enabling device isolation [checkbox](https://github.com/sandboxie-plus/Sandboxie/pull/1481#issuecomment-1253320292), a supporter certificate is still required and not everyone wants it.

The only thing I can adjust for your [use case](https://github.com/sandboxie-plus/Sandboxie/issues/1102#issuecomment-993016787) consists to limit the existing restriction only for the VMware tool that writes the change instead of closing completely the virtual network access to your VM.

It is inconceivable that Sandboxie cannot retain a virtual device within standard sandboxes by default, but this is the reality and I do not have the technical knowledge to do so.

Also, I'm against introducing a new template that could hide the attention to a serious issue not completely fixed.

**Pull request merged**
