### PR TITLE
Update Ru Translation

### PR DESCRIPTION
**Pull request by lufog**

### CODE REVIEW

**Review by isaak654 — CHANGES_REQUESTED** [review]
Please consider to address the issues found by the Parse script: [Report-Russian.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/report/Report-Russian.txt)

**Comment by lufog** [comment]
Ok, I'll try, but it will take some time.

**Comment by lufog** [comment]
@isaak654, done.

**Review by isaak654 — APPROVED** [review]
I have just generated a new language report manually (after applying your latest commit) in my fork through the GitHub Actions tab and everything is fine. This is something I can only recommend to all translators in the future.

**Pull request merged**
