### PR TITLE
Fix old references

### PR DESCRIPTION
**Pull request by isaak654**
Feel free to report further inconsistencies.

### CODE REVIEW

**Comment by DavidXanatos** [comment]
should be working lets merge it and try if all instalers build fine

**Review by offhub — APPROVED** [review]

**Comment by isaak654** [comment]
I had some doubts in merging the original [SandboxiePlus/SandMan/LICENSE](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE), because it has an [initial part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L4-L6) (probably incomplete) that I discarded, while I copied the [missing part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L26-L48) related to the usage of the source code into LICENSE.Plus.

So if you merge the pull request, you will approve the content changes to the license as well.

**Comment by isaak654** [comment]
I had some doubts in merging the original [SandboxiePlus/SandMan/LICENSE](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE), because it has an [initial part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L4-L6) (probably incomplete) that I discarded, while I copied the [missing part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L26-L48) related to the usage of the source code into LICENSE.Plus.

So if you merge the pull request, you will also approve the content changes to the Plus license (in order to avoid duplication and keep a certain consistency).

**Comment by isaak654** [comment]
I had some doubts in merging the original [SandboxiePlus/SandMan/LICENSE](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE) because it has an [initial part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L4-L6) (probably incomplete) that I discarded, while I copied the [missing part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L26-L48) related to the usage of the source code into LICENSE.Plus.

So if you merge this pull request, you will also approve the content changes to the Plus license in order to keep a certain consistency.

**Comment by isaak654** [comment]
I had some doubts in merging the original [SandboxiePlus/SandMan/LICENSE](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE) because it has an [initial part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L4-L6) (probably incomplete) that I discarded, while I copied the [missing part](https://github.com/sandboxie-plus/Sandboxie/blob/1ffa7a0a7d9a418f2ee9cb7f40f99333b090843c/SandboxiePlus/SandMan/LICENSE#L26-L48) related to the usage of the source code into LICENSE.Plus.

So if you merge this pull request, you will also approve the content changes to the Plus license in order to maintain some consistency and unify all the duplicate Plus licenses I found into one.

**Comment by DavidXanatos** [comment]
hmm... right... 
mmh... I think the license for the installer, which installs only the binaries should be short so there we can keep it as it was.
like its with the classic installer there the license.txt is also the short version

Also /Sandboxie/COPYING is redundant with the Lincense.classic so we should remove it

**Comment by DavidXanatos** [comment]
i have restored the file with the short version in the installer directory and one more, mow i think there are no links but some repetitions which is ok lets leave sandboxie/copying and sandboxieplus/sandman/license where they are

**Pull request merged**
