### PR TITLE
Add all U.N.  official language support to documentation

### PR DESCRIPTION
**Pull request by SNESNya**
~~This PR contributes support for zh-CN documents so that Chinese users can get started better. This translation follows the "Localization notes and tips" and only translates the documents.~~

I will provide support for this document in all UN languages.This PR is still being edited

### CODE REVIEW

**Comment by SNESNya** [comment]
I accidentally clicked the wrong button. I didn't click Draft. Sorry.

**Comment by love-code-yeyixiao** [comment]
> I accidentally clicked the wrong button. I didn't click Draft. Sorry.

You can use "Convert to draft" if you need.

**Comment by love-code-yeyixiao** [comment]
I'm really not sure if this PR can be merged, after all Chinese is only a small part of the supported languages for this project, not sure if others will think it's unfair, to be on the safe side it's recommended to at least add all the UN working languages.(You can ignore that too. I'm just worried.)

**Comment by SNESNya** [comment]
> I'm really not sure if this PR can be merged, after all Chinese is only a small part of the supported languages for this project, not sure if others will think it's unfair, to be on the safe side it's recommended to at least add all the UN working languages.(You can ignore that too. I'm just worried.)

I will try to translate all UN languages in the next few days. I may use ChatGPT, but I will make sure the translation is of very good quality.

**Comment by SNESNya** [comment]
> I'm really not sure if this PR can be merged, after all Chinese is only a small part of the supported languages for this project, not sure if others will think it's unfair, to be on the safe side it's recommended to at least add all the UN working languages.(You can ignore that too. I'm just worried.)

I have submitted documents in all UN languages, can they be merged?

**Comment by love-code-yeyixiao** [comment]
I think that's enough, @DavidXanatos will maybe merge it.So far I don't have merge access.

**Comment by isaak654** [comment]
Nowadays, all browsers have a built-in translation tool with a good approximation, what is the purpose of translating Markdown documents? That said, I would like to hear other opinions.

**Comment by DavidXanatos** [comment]
Is that required? Shouldn't nowadays all Internet users be sufficiently fluent in English to be fine with an English only documentation? 

My main worry is I guess that the non English versions will end up outdated, so unless we can AI generate always up to date translations, it may be more problems that its worth.
Even MSFT uses AI for their non English MSDN articles AFAIK.

**Comment by diversenok** [comment]
The translations in the pull request are clearly machine-generated and are relatively low-quality. Anybody can get the same result by using the built-in browser feature.

**Comment by SNESNya** [comment]
I use ChatGPT 4o and Claude 3.5 Sonnets, which I think are very strong.
Moreover, I bought GPT Plus

diversenok ***@***.***> 于 2024年8月1日周四 下午10:15写道：

**Comment by isaak654** [comment]
> My main worry is I guess that the non English versions will end up outdated, so unless we can AI generate always up to date translations, it may be more problems that its worth.
> Even MSFT uses AI for their non English MSDN articles AFAIK.

I have found [Markdown Translator Action](https://github.com/marketplace/actions/markdown-translator), would anyone like to volunteer?

**Comment by DavidXanatos** [comment]
BTW: talking about translation what about this weblate I installed, if no one knows how to properly use this I should close that server as it costs money.

**Comment by isaak654** [comment]
> BTW: talking about translation what about this weblate I installed, if no one knows how to properly use this I should close that server as it costs money.

If there is no way to get help for [reported issues](https://github.com/sandboxie-plus/Sandboxie/issues/3293#issuecomment-1784143293), so be it.

**Pull request closed without merging**
