### PR TITLE
Display PDF/Print category in Plus UI

### PR DESCRIPTION
**Pull request by isaak654**
@DavidXanatos I need a review about the validity of this commit. 
The scope of this commit is to rename the Print category to PDF/Print (only in Plus UI).

### CODE REVIEW

**Comment by isaak654** [comment]
@DavidXanatos I need a review about this commit. 
The scope of this commit is to rename the Print category to PDF/Print (only in Plus).

**Comment by isaak654** [comment]
@DavidXanatos I need a review about the validity of this commit. 
The scope of this commit is to rename the Print category to PDF/Print (only in Plus UI).

**Comment by DavidXanatos** [comment]
GetTemplateNames returns a string list you can not use "bla" + string list
The goal is to change the category name in the UI as displayed in the template list and the filter combo box right?

**Comment by isaak654** [comment]
> 
> 
> GetTemplateNames returns a string list you can not use "bla" + string list
> The goal is to change the category name in the UI as displayed in the template list and the filter combo box right?

Yeah, this is needed **only** in the Plus UI, not in Classic UI.
It would allow to avoid to replace the Print variable in the `Tmpl.Class=Print` entries listed in templates.ini.

**Pull request closed without merging**
